version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/Uks
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=Uks
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    restart: always
    
volumes:
  pgdata:
