# Generated by Django 3.1.5 on 2021-01-29 15:36

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, verbose_name='username')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('first_name', models.CharField(max_length=500, verbose_name='first name')),
                ('last_name', models.CharField(max_length=500, verbose_name='last name')),
                ('email', models.EmailField(max_length=500, verbose_name='email')),
                ('password', models.EmailField(max_length=500, verbose_name='password')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='user.userproxy')),
            ],
            options={
                'verbose_name': 'GitHub user',
                'verbose_name_plural': 'GitHub users',
            },
        ),
    ]
