# Generated by Django 3.1.5 on 2021-02-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('milestone', '0001_initial'),
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('openingDate', models.DateTimeField(auto_now_add=True)),
                ('taskStatus', models.CharField(choices=[('TO_DO', 'TO_DO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('TEST', 'TEST'), ('DONE', 'DONE')], default='TO_DO', max_length=50)),
                ('taskState', models.CharField(choices=[('OPENED', 'OPENED'), ('CLOSED', 'CLOSED')], default='OPENED', max_length=50)),
                ('taskPriorty', models.CharField(choices=[('LOW', 'LOW'), ('MEDUIM', 'MEDUIM'), ('HIGH', 'HIGH')], default='LOW', max_length=50)),
                ('taskType', models.CharField(choices=[('BUG_FIX', 'BUG_FIX'), ('FEATURE', 'FEATURE')], default='FEATURE', max_length=50)),
                ('asignees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('labels', models.ManyToManyField(blank=True, to='label.Label')),
                ('milestone', models.ManyToManyField(blank=True, to='milestone.Milestone')),
                ('project', models.ManyToManyField(blank=True, to='project.Project')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo', to='repository.repository')),
            ],
        ),
    ]
