# Generated by Django 3.1.5 on 2021-01-29 15:36

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('openingDate', models.DateTimeField(auto_now_add=True)),
                ('closingDate', models.DateTimeField(null=True)),
                ('taskStatus', models.CharField(choices=[(task.models.TaskStatus['TO_DO'], 'TO_DO'), (task.models.TaskStatus['IN_PROGRESS'], 'IN_PROGRESS'), (task.models.TaskStatus['TEST'], 'TEST'), (task.models.TaskStatus['DONE'], 'DONE')], default='TO_DO', max_length=50)),
                ('taskState', models.CharField(choices=[(task.models.TaskState['OPENED'], 'OPENED'), (task.models.TaskState['CLOSED'], 'CLOSED')], default='OPENED', max_length=50)),
                ('taskPriorty', models.CharField(choices=[(task.models.TaskPriorty['LOW'], 'LOW'), (task.models.TaskPriorty['MEDUIM'], 'MEDUIM'), (task.models.TaskPriorty['HIGH'], 'HIGH')], default='LOW', max_length=50)),
                ('taskType', models.CharField(choices=[(task.models.TaskType['BUG_FIX'], 'BUG_FIX'), (task.models.TaskType['FEATURE'], 'FEATURE')], default='FEATURE', max_length=50)),
                ('label', models.ManyToManyField(to='label.Label')),
            ],
        ),
    ]
