# Generated by Django 3.1.5 on 2021-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('task', '0002_auto_20210129_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='asignees',
            field=models.ManyToManyField(blank=True, to='user.UserModel'),
        ),
    ]
